# Use a base image with Java
FROM openjdk:21-jdk-slim as builder

# Set the working directory
WORKDIR /app

# Copy the Maven or Gradle build file
COPY mvnw ./
COPY .mvn .mvn
COPY pom.xml .

# Ensure mvnw has execute permissions
RUN chmod +x ./mvnw

# Copy source code
COPY src ./src

# Build the application
ARG ENV=production
RUN if [ "$ENV" = "production" ]; then ./mvnw package -DskipTests; else ./mvnw clean package -DskipTests; fi

# Use a smaller image to run the application
FROM openjdk:21-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the jar file from the builder stage
COPY --from=builder /app/target/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

# Use a separate command for development
CMD ["java", "-jar", "app.jar"]