name: CI/CD for Pollster app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK for Maven build and tests
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # List files for debugging
      - name: List files
        run: ls -R

      # Set executable permissions for Maven Wrapper
      - name: Set permissions
        run: chmod +x ./PollsterAPI/mvnw

      # Run Maven clean and build
      - name: Build with Maven
        run: |
          cd PollsterAPI
          ls 
          chmod +x ./mvnw
          ./mvnw clean package

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          cd PollsterAPI
          chmod +x ./mvnw
          ./mvnw clean test

      # Clean up any conflicting Docker/containerd packages
      - name: Clean up conflicting Docker packages
        run: |
          sudo apt-get remove --purge -y containerd containerd.io docker docker.io docker-ce docker-ce-cli
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo apt-get update

      # Install Docker and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          # Install Docker
          sudo apt-get update
          sudo apt-get install -y docker.io

          # Install Docker Compose (ensure the correct version and location)
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

          # Check if the file is downloaded and has content
          ls -l /usr/local/bin/docker-compose
          file /usr/local/bin/docker-compose
          
          # Set correct permissions
          sudo chmod +x /usr/local/bin/docker-compose

          # Verify installations
          docker --version
          docker-compose --version

      # Set up SSH access for deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Build and push Docker images to the Docker registry (if applicable)
      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      # Deploy to EC2 instance
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Debugging: Check working directory and Docker Compose version
            echo "Working Directory: $(pwd)"
            docker-compose --version

            # Pull the latest code and navigate to the project directory
            cd /home/ubuntu/Polllster
            git pull origin master

            # Ensure Docker Compose is working and update containers
            docker-compose down
            #docker-compose pull
            docker-compose build --no-cache
            docker-compose up -d
          EOF
